### ISSUE TITLE
Positive 和 Negative Set 问题

### ISSUE THREAD

**Issue by ly0303521** [CaptainEven/RepNet-MDNet-VehicleReID#2]
你好，我看到论文上面有Positive 和 Negative 训练集，但是在代码中貌似没有看到这个思想的体现，代码是不是没有完全按照论文的方法来实现？？

**Comment by CaptainEven** [comment]
@ly0303521 您好，这里为了简化实现，用arc loss代替了triplet loss，所以不需要用triplet set进行训练，达到的效果是一样的：提取细粒度具有分辨力的特征。如果对triplet sampling感兴趣可以参考https://github.com/CaptainEven/FaceRecognition

**Comment by ly0303521** [comment]
OK， 非常感谢这么快速的解答
