### ISSUE TITLE
汽车品牌型号

### ISSUE THREAD

**Issue by world2025** [CaptainEven/RepNet-MDNet-VehicleReID#21]
你好，请问你有做过汽车品牌型号分类和识别吗？例如奥迪有Q5、Q3系列，通过车的图片来识别车的品牌具体型号

**Comment by CaptainEven** [comment]
@tkone2018 使用VehicleID数据集和本repo的代码可以做品牌(型号)识别，可以参考#1

**Comment by world2025** [comment]
ahha,可以吗？我看了下数据集的名，没看到品牌对应标签呀

**Comment by CaptainEven** [comment]
参考rep中的model_names.txt：
五菱荣光2008款 0
大众-朗逸2006-2011 1
奥迪A6L-2012款 2
丰田-普拉多-2004-2006 3
奔驰-R级2010款 4
长城-C30-2012款 5
雪铁龙-凯旋 6
起亚-智跑 7
日产(尼桑)-天籁2014款 8
雪铁龙-世嘉2009-2011款 9
现代-途胜-2009 10
本田-飞度-2008款 11
日产(尼桑)-奇骏-2008款 12
福田面包车 13
三菱-欧蓝德2006-2012款 14
斯柯达-晶锐 15
起亚-索兰托2009-2013款 16
别克-英朗2010-13款 17
金杯-海狮-2013款 18
现代-伊兰特11款 19
丰田-普拉多2010 20
丰田-rava-4-2009款 21
雪铁龙-爱丽舍-2014款 22
本田-思域2012-2013款 23
现代-名驭 24
奔驰-GLK级2013款 25
沃尔沃XC60 26
海马-M3 27
现代-悦动-2008 28
MG5 29
江铃凯运轻卡 30
比亚迪F6 31
哈弗-哈弗H5-2011-2013款 32
比亚迪F0 33
MG3-2008款 34
福特-嘉年华2009 35
海马-王子 36
标致-207 37
日产(尼桑)-天籁2007款 38
现代-胜达13款 39
依维柯-TurboDaily 40
福特-福克斯2012款 41
长安之星6363系列 42
现代-瑞纳-2010 43
长安之星2代 44
奇瑞-瑞虎2011款 45
奥迪-Q5 46
奔驰-S级2011款 47
大众-速腾2006-2011款 48
现代-胜达2012款 49
马自达6-2008款 50
哈弗-哈弗H3-2012款 51
现代-途胜-2008 52
大众-桑塔纳2004款 53
丰田-凯美瑞2009款 54
雪佛兰-科帕奇 55
大众-速腾2012-2014款 56
雪佛兰-乐风 57
比亚迪S6 58
沃尔沃-xc90 59
铃木-天语2009 60
解放-赛麒麟 61
起亚-锐欧-2007款 62
雪铁龙-C4L 63
马自达6-2011-2013款 64
奥迪A4-2009-2012款 65
奔驰-E级2012款 66
五菱宏光 67
别克-昂科拉 68
别克-君威09-11款 69
别克-凯越 70
宝马3系2013-2014款 71
别克-GL8-06-08款 72
三菱-蓝瑟2010款 73
宝马X5 74
奇瑞-风云 75
丰田-凯美瑞2008款 76
奇瑞-A5 77
日产(尼桑)-轩逸2007-2012新款 78
马自达2 79
日产(尼桑)-奇骏-2012款 80
海马-普力马2010款 81
长安星光SC6345BFA 82
昌河-福瑞达 83
现代-索纳塔11款 84
标致-206 85
现代-悦动-2011 86
铃木-雨燕2012-2013款 87
斯柯达-明锐 88
奇瑞-A3-2008 89
丰田-威驰2008 90
长城-C30-2013-2014款 91
现代-朗动-2012 92
丰田-威驰2010-2013 93
奇瑞-旗云-2008款 94
金杯-海狮-2008款 95
马自达3-2010-2012款 96
雪佛兰-景程 97
标致-307 98
马自达3-2006-2008款 99
斯巴鲁-森林人2012款 100
中华-骏捷2007 101
奔驰-C级2011款 102
大众-途观 103
东风景逸-2014款 104
别克-君越2009-2013款 105
现代-ix35 106
奥迪-Q7 107
宝马X6 108
丰田-花冠2009款 109
三菱-劲炫 110
雷克萨斯-ES2013-2014款 111
荣威350-2011 112
奥迪A6L-2009款 113
丰田-威驰2004 114
斯巴鲁-傲虎2010款 115
五菱之光2007款 116
本田-雅阁2011-2013款 117
本田-思域2009款 118
现代-索纳塔14款 119
奇瑞-QQ-2007-2012款 120
丰田-凯美瑞2012款 121
中华-骏捷2011款 122
现代-领翔2009款 123
标致308-2012-1013款 124
奥迪-A8L 125
别克-英朗XT 126
东风风行-菱智2014款 127
斯柯达-昊锐 128
宝马530 129
起亚-狮跑2012-2013款 130
本田-奥德赛-2011款 131
吉利-帝豪 132
丰田-汉兰达 133
解放-悍威（J5M）重卡 134
奥迪A4-2013款 135
宝马-7系 136
雷克萨斯-ES2009-2010款 137
东南-得利卡 138
申沃-swb6940 139
宝马五系 140
哈弗-哈弗H6 141
雪铁龙-C2 142
福特-嘉年华2004款 143
日产(尼桑)-天籁2011款 144
雷克萨斯-ES2006款 145
五菱之光2013款 146
MINI-cooper-2008-2010款 147
比亚迪L3 148
丰田-凯美瑞2013款 149
荣威350-2010款 150
现代-ix35-2012款 151
福特-福克斯2009款 152
依维柯-宝迪 153
比亚迪F3-2007-2011款 154
日产(尼桑)-骐达-骐达2008-2009款 155
凯迪拉克SRX 156
起亚-K5-2012款 157
宝马X3 158
丰田-皇冠 159
斯巴鲁-森林人2008款 160
奇瑞-瑞虎2009-2013 161
jeep-指南者 162
中华-威志 163
日产(尼桑)-轩逸-轩逸2007-2012经典款 164
日产(尼桑)-骐达-骐达-2011款 165
雪铁龙-爱丽舍2008-2013款 166
宝马-X1 167
江淮-和悦2010款 168
大众-波罗 169
起亚-狮跑2007-2009款 170
宝马3系2007-2012款 171
雪佛兰-科鲁兹 172
丰田-卡罗拉2008款 173
东风重货车 174
福特-蒙迪欧 175
江淮-瑞风-2012款 176
海马-海福星-2007款 177
东风风行-景逸-2008款 178
申沃-sw6127lng 179
申沃-swb5115gp 180
起亚-k2 181
东风小康 182
大众-捷达2008 183
本田-思威2005-2010款 184
标致-408-10-11款 185
雷诺-科雷傲2012款 186
金杯-阁瑞斯MPV-2008款 187
比亚迪G3 188
解放-赛龙中卡 189
东风风度-帅客 190
大众-宝来2013-2014 191
丰田-雅力士 192
大众-迈腾2011-2013款 193
荣威750-2008款 194
依维柯-都灵v 195
荣威550 196
铃木-北斗星 197
别克-GL82011-2013款 198
铃木-雨燕2007-2008款 199
江淮-同悦A13-2008款 200
雪铁龙-C5-2010-2012款 201
哈飞-民意 202
福田-奥铃TX 203
丰田-花冠2013款 204
福特-福克斯2010款 205
东南-v3凌悦 206
雷诺-科雷傲2009-2010款 207
海马-福美来 208
大众-迈腾2009款 209
本田-锋范-2009款 210
日产(尼桑)-阳光2011-2014款 211
本田-思威2012-2013款 212
雪佛兰-爱唯欧 213
起亚-K3-2012款 214
福特-翼博 215
东风风行-菱智2013款 216
福特-福克斯2006款 217
丰田-卡罗拉2012款 218
路虎-发现2010-2014款 219
日产(尼桑)-骊威-骊威2008-2010款 220
雪铁龙-世嘉-2012款 221
现代-伊兰特2007款 222
雷诺-科雷傲2013-2014款 223
雪佛兰-赛欧 224
起亚-赛拉图2005-2007款 225
大众-帕萨特 226
大众-高尔夫2006-2012 227
大众-朗逸2012-2014 228
五菱扬光 229
起亚-赛拉图2008-2012款 230
雪铁龙-C4-2009款 231
本田-歌诗图 232
长安之星 233
起亚-福瑞迪-福瑞迪2009款 234
大众-捷达2010-2013 235
雪佛兰-迈锐宝 236
奇瑞-E5 237
东风风行-x5 238
福田-奥铃CTX 239
大众-桑塔纳2013款 240
日产(尼桑)-逍客-逍客2011-2012款 241
长安星光4500系列 242
铃木-奥拓2013款 243
大众-宝来2008-2012 244
长城-M4-2012款 245
丰田-锐志2008 246
江淮-和悦RS-2010款 247
丰田-花冠2011款 248
奔驰-M级2012款 249

**Comment by world2025** [comment]
model_attr.txt这个文件是每个图片对应的品牌标签是吗？也就是不是每张图片都给品牌标签了是吗？

**Comment by CaptainEven** [comment]
@tkone2018 建议仔细研究下VehicleID数据集，每张图片都有标签。

**Comment by world2025** [comment]
好的，谢谢，我再细致了解一下
