### ISSUE TITLE
用实际图片，模型预测不准确

### ISSUE THREAD

**Issue by xagpx** [CaptainEven/RepNet-MDNet-VehicleReID#24]
![image](https://user-images.githubusercontent.com/13012069/93709241-5ab56380-fb6f-11ea-849e-383554924c2b.png)

**Comment by CaptainEven** [comment]
跟训练数据集有关，如果要应用到自定义场景，需要添加相应的训练数据集。深度学习的任何测试都是针对特定的数据集进行的。

**Comment by qiuqiuzyq** [comment]
你这是直接用模型跑的吗？你是怎么测试的呀？我只看到有训练代码诶。。能指点一下吗，谢谢啦
![~G P080M95V_2}T VUZ@@E4](https://user-images.githubusercontent.com/59553017/93988555-701ecd80-fdbb-11ea-9df4-34efef6048c7.png)

**Comment by xagpx** [comment]
> 跟训练数据集有关，如果要应用到自定义场景，需要添加相应的训练数据集。深度学习的任何测试都是针对特定的数据集进行的。

测试的数据集是要求俯拍正面图片吗
