### ISSUE TITLE
related to test

### ISSUE THREAD

**Issue by Jack12xl** [CaptainEven/RepNet-MDNet-VehicleReID#4]
如果没理解错的话，代码里仅对同时有model和color的数据集进行了train和test，那请问下test的时候有跑过整个test dataset(包括没有model或color)的实验嘛

**Comment by CaptainEven** [comment]
@Jack12xl 根据论文中的网络结构需要的训练数据是包含model和color的，test的时候可以对所有数据进行test，不过我这里偷懒没有做。

**Comment by Jack12xl** [comment]
ok多谢

**Comment by tkone2018** [comment]
@CaptainEven ，你好，请问你解决了demo没标签的数据吗？谢谢！

**Comment by world2025** [comment]
@Jack12xl 你好，请问你解决了无model标签的图像测试问题吗？

**Comment by Jack12xl** [comment]
@tkone2018 时间隔得有点久，没记错的话后面还是选择直接剃掉了无label的数据

**Comment by world2025** [comment]
@Jack12xl 好的
