### ISSUE TITLE
关于网络输入输出的维度

### ISSUE THREAD

**Issue by ideaflow** [CaptainEven/RepNet-MDNet-VehicleReID#8]
想请教一下，初始化网络的时候这两个参数 “out_ids=10086” 和 “out_attribs=257” 分别代表什么呢？这两个取值是如何确定的？如果要新增自己需要识别的车辆品牌，是否需要修改这两个值？
![tmp](https://user-images.githubusercontent.com/21287382/61586644-1665b680-abac-11e9-8ad8-dfcab4edf1ba.PNG)

**Comment by CaptainEven** [comment]
@ideaflow 请参考VehicleID数据集的处理脚本ProcessVehicleID.py
